AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java + RDS Lambda Function
Resources:
  ClaimsProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ClaimsProcessor
      Handler: org.octank.claims.main.ClaimsProcessingHandler
      Runtime: java8
      CodeUri: s3://octank-healthcare/octank-claims-lambda-1.0-SNAPSHOT.jar
      Description: Manage Claims
      Timeout: 30
      MemorySize: 1024
      VpcConfig: # For accessing RDS instance
        SecurityGroupIds:
          - sg-0ea026c0ff58ab0f1
        SubnetIds:
          - subnet-7e153824 
          - subnet-be396bc7 
          - subnet-379ae67c
      Environment:
        Variables:
          RDS_HOSTNAME: claimsdii-cluster-1.cluster-clfzy7tgfzlq.us-west-2.rds.amazonaws.com:3306
          RDS_DB_NAME: CLAIMS
          RDS_USERNAME: claimsmaster
          RDS_PASSWORD: claims123
      Role: arn:aws:iam::716664005094:role/microServiceRole
